//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhimDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGom
    {
        public int BaoGomID { get; set; }
        public int LichChieuID { get; set; }
        public int PhimID { get; set; }
    
        public virtual LichChieu LichChieu { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
