//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhimDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BaoGoms = new HashSet<BaoGom>();
            this.XuatChieux = new HashSet<XuatChieu>();
        }
    
        public int PhimID { get; set; }
        public string Ten { get; set; }
        public string DaoDien { get; set; }
        public string DienVien { get; set; }
        public string TheLoai { get; set; }
        public string PhienBan { get; set; }
        public string HangPhim { get; set; }
        public string NuocSanXuat { get; set; }
        public int DoDai { get; set; }
        public string Poster { get; set; }
        public string GioiThieu { get; set; }
        public string Trailer { get; set; }
        public string Pdf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoGom> BaoGoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatChieu> XuatChieux { get; set; }
    }
}
