//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhimDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int VeID { get; set; }
        public bool TrangThai { get; set; }
        public int XuatChieuID { get; set; }
        public int GheID { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual XuatChieu XuatChieu { get; set; }
    }
}
