//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhimDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XuatChieu()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int XuatChieuID { get; set; }
        public System.DateTime Ngay { get; set; }
        public int LichChieuID { get; set; }
        public int CaChieuID { get; set; }
        public int PhongID { get; set; }
        public int PhimID { get; set; }
    
        public virtual CaChieu CaChieu { get; set; }
        public virtual LichChieu LichChieu { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
